---
title: "TidyTemplate"
date: 2024-05-03
output: html_document
---

# Worldwide Bureaucracy Indicators


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(camcorder)
library(here)
library(glue)
library(ggtext)
library(showtext)
library(extrafont)
library(geomtextpath)

```



```{r}
tt_source <- "Rolling Stones Top 500 Albums"  
bg_color <- "#ffffff"
txt_color <- "black"
txt_color2 <- "#20C29D"

yellow <- "#FFB702"  
blue <- "#1E9BD5"
green <- "#20C29D"
light_blue <- "#00E7EC"
red <- "#FF5674"

tt_family <- "montserrat"
tt_family_2 <-  "roboto"


font_add_google("Montserrat", tt_family)
font_add_google("Roboto", tt_family_2)

# font_add("fa-brands",
#          regular = here("Assets","Fonts","fontawesome-free-6.4.2-web","webfonts","fa-brands-400.ttf"))
# font_add("fa-solid",
#          regular = here("Assets","Fonts","fontawesome-free-6.4.2-web","webfonts","fa-solid-900.ttf"))
# font_add("fa-regular",
#          regular = here("Assets","Fonts","fontawesome-free-6.4.2-web","webfonts","fa-regular-400.ttf"))
# showtext_auto(enable = T) 

X  <- str_glue("<span style='font-family:fa-brands'>&#xe61b;</span>")
GH <- str_glue("<span style='font-family:fa-brands'>&#xf09b;</span>")
MN <- str_glue("<span style='font-family:fa-brands'>&#xf4f6;</span>")
DT <- str_glue("<span style='font-family:fa-brands'>&#xf1c0;</span>")

tt_caption <- str_glue(
  "Karina Jonina #TidyTuesday 2024-30-04<br>
  {X} @karinajonina {GH} @kjonina {MN} @kjonina<br>
  Data: {tt_source}
  "
)

tt_title_text    <- str_glue("Rolling Stones Top 500 Albums")

```

# Load the weekly Data

```{r Load}

tt <- tt_load("2024-05-07")

```


# Readme

```{r Readme, eval = interactive()}

tt

```


# Glimpse Data

```{r Glimpse}

tt %>% 
  map(glimpse)

```

# Wrangle

```{r Wrangle}
rolling_stone <- tt$rolling_stone

```
# Exploring Data

```{r Cleaning Data}


df <- rolling_stone %>%
  select(release_year, genre, spotify_popularity) %>%
  filter(!is.na(spotify_popularity)) %>%
  group_by(release_year, genre) %>%
  summarise(count = n(),
            min_spotify_popularity = min(spotify_popularity, na.rm = TRUE),
            median_spotify_popularity = median(spotify_popularity, na.rm = TRUE),
            mean_spotify_popularity = mean(spotify_popularity, na.rm = TRUE),
            max_spotify_popularity = max(spotify_popularity, na.rm = TRUE),
            std_spotify_popularity = sd(spotify_popularity, na.rm = TRUE)
            ) %>%
  ungroup()



rolling_stone %>% 
  filter(grepl("Rock", genre, ignore.case = TRUE))
	


albums_not_on_spotify <- rolling_stone %>%
  filter(is.na(spotify_popularity)) 



```


```{r}
rolling_stone_pivot_longer <-rolling_stone %>%
  mutate(across(c(rank_2003, rank_2012, rank_2020), ~replace(., is.na(.), 501))) %>%
  pivot_longer(cols = c(rank_2003, rank_2012, rank_2020),
               names_to = "rank_year", values_to = "rank") %>%
  mutate(rank_year = if_else(rank_year == "rank_2020", "2020", rank_year),
         rank_year = if_else(rank_year == "rank_2012", "2012", rank_year),
         rank_year = if_else(rank_year == "rank_2003", "2003", rank_year)) %>%
  mutate(rank_year = as.factor(rank_year)) %>%
  mutate(rank_year = fct_relevel(rank_year, "2003", "2012", "2020")) 


#################################
artists_with_most_albums_in_Top10 <- rolling_stone_pivot_longer %>%
  select(clean_name,rank_year, rank ) %>%
  filter(!is.na(rank)) %>%
  group_by(clean_name) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(10)

Album_with_most_weeks_on_billboard <- rolling_stone_pivot_longer %>%
  select(album, clean_name, weeks_on_billboard,release_year,  rank ) %>%
  filter(!is.na(rank)) %>%
  arrange(desc(weeks_on_billboard)) %>%
  distinct(clean_name, album,release_year, weeks_on_billboard) %>%
  head(20)


#################################
# Is Elvis Dead?
#################################

is_elvis_dead <- rolling_stone_pivot_longer %>%
  filter(clean_name == "Elvis Presley") %>%
  filter(!is.na(rank)) %>%
  select(clean_name, album, release_year, rank_year, rank)




#################################
# My favourite artists
#################################
my_favourite_artist <- c("Adele", "Taylor Swift", "Rihanna", "Linkin Park","Chris Cornell", "Soundgarden",  "Dua Lipa")

favourites <- rolling_stone_pivot_longer %>%
  filter(clean_name %in% my_favourite_artist) %>%
  filter(!is.na(rank)) %>%
  select(clean_name, album, release_year, rank_year, rank)




#################################
# Is Rock'n'Roll Dead?
#################################

is_rock_n_roll_dead <- rolling_stone_pivot_longer %>%
  filter(!is.na(rank)) %>%
  select(clean_name, album, genre, rank_year, rank)%>%
  mutate(rock_status = if_else(str_detect(str_to_lower(genre), "rock n' roll"), "Rock n' Roll", "not Rock n' Roll")) %>%
  replace_na(list(rock_status = "Unknown")) %>%
  filter(!is.na(rank))

#################################
is_rock_n_roll_dead_2 <- is_rock_n_roll_dead %>%
  filter(rock_status == "Rock n' Roll") %>%
  mutate(album_artist = paste(album, clean_name, sep = " - ")) %>%
  arrange(desc(rank_year), rank)


ggplot(is_rock_n_roll_dead_2, aes(x = rank_year, y = rank, color = album_artist)) + 
  geom_point() +
  geom_line(aes(x = rank_year, y = rank, color = album_artist)) +
  labs(title = "Scatter Plot of Rank Over Years",
       x = "Year",
       y = "Rank",
       color = "Group") +
  theme_minimal()
```
```{r}
top_20_albums_in_2003 <- rolling_stone_pivot_longer %>%
  filter(rank_year == "2003") %>%
  filter(rank != 501) %>%
  select(clean_name, album, rank_year, rank) %>%
  arrange(rank) %>%
  head(20) %>%
  select(album) %>%
  pull()



# How do they hold up in 2012 and 2020
#################################
top_20_albums_in_2003_charts <- rolling_stone_pivot_longer %>%
  filter(album %in% top_20_albums_in_2003) %>%
  select(clean_name, album, rank_year, rank) %>%
  mutate(album_artist = paste(album, clean_name, sep = " - ")) 

ggplot(top_20_albums_in_2003_charts, aes(x = rank_year, y = rank, color = album_artist)) + 
  geom_point() +
  geom_line(aes(x = rank_year, y = rank, color = album_artist)) +
  labs(title = "Scatter Plot of Rank Over Years",
       x = "Year",
       y = "Rank",
       color = "Group") +
  theme_minimal()
```


# Visualize

Using your processed dataset, create your unique visualization.

```{R Setting Saving Options}
camcorder::gg_record(dir = here("outputs"),
  device = "png",
  width = 8, height = 7,
  units = "in", dpi = 320
  )
```
  


```{r}

df %>%
ggplot(aes(x = table_name, y = value)) +
  geom_line(linewidth=1.25) +
  

  labs(title = tt_title_text,
       # subtitle = tt_subtitle_text,
       caption = tt_caption,
       colour = "",
       x = "Countries",
       y = "Cumulative Count") + 
 theme( 
   
    plot.background = element_rect(colour=bg_color,fill = bg_color),
    panel.background = element_rect(colour=bg_color,fill = bg_color),
    
    plot.title.position = "plot",
    plot.title = element_textbox_simple(
      halign = 0.5,
      tt_family_2,
      color = txt_color,
      face = "bold",
      size = 100,
      margin = margin(t = 2, r = 0, b = 0, l = 0)
    ),
    
    plot.subtitle = element_textbox_simple(
      halign = 0.5,
      tt_family,
      color = txt_color2,
      #face = "bold",
      size = 80,
      margin = margin(t = 1, r = 0, b = 2, l = 0)
    ),
    
    plot.caption = element_textbox_simple(
      family = tt_family, 
      color = txt_color,
      size = 25,
      lineheight = 0.25,
      margin = margin(t = 1, r = 0, b = 1, l = 2)
    ),
    
    axis.text.x = element_text(size=40,family = tt_family),
    axis.text.y = element_text(size=30,family = tt_family),
    axis.title.x = element_text(size=40,family = tt_family),
    axis.title.y = element_text(size=30,family = tt_family),
    panel.grid.major.y = element_line(colour="black", size=0.1),
    panel.grid.major.x = element_blank(),

    plot.caption.position = "plot",
    legend.position = "none"
    

  )
```


