---
title: "TidyTemplate"
date: 2024-05-03
output: html_document
---

# Worldwide Bureaucracy Indicators


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(camcorder)
library(here)
library(glue)
library(ggtext)
library(showtext)
library(extrafont)
library(geomtextpath)

```



```{r}
tt_source <- "Worldwide Bureaucracy Indicators"
bg_color <- "#ffffff"
txt_color <- "black"
txt_color2 <- "#20C29D"

yellow <- "#FFB702"  
blue <- "#1E9BD5"
green <- "#20C29D"
light_blue <- "#00E7EC"
red <- "#FF5674"

tt_family <- "montserrat"
tt_family_2 <-  "roboto"


font_add_google("Montserrat", tt_family)
font_add_google("Roboto", tt_family_2)

# font_add("fa-brands",
#          regular = here("Assets","Fonts","fontawesome-free-6.4.2-web","webfonts","fa-brands-400.ttf"))
# font_add("fa-solid",
#          regular = here("Assets","Fonts","fontawesome-free-6.4.2-web","webfonts","fa-solid-900.ttf"))
# font_add("fa-regular",
#          regular = here("Assets","Fonts","fontawesome-free-6.4.2-web","webfonts","fa-regular-400.ttf"))
# showtext_auto(enable = T) 

X  <- str_glue("<span style='font-family:fa-brands'>&#xe61b;</span>")
GH <- str_glue("<span style='font-family:fa-brands'>&#xf09b;</span>")
MN <- str_glue("<span style='font-family:fa-brands'>&#xf4f6;</span>")
DT <- str_glue("<span style='font-family:fa-brands'>&#xf1c0;</span>")

tt_caption <- str_glue(
  "Karina Jonina #TidyTuesday 2024-30-04<br>
  {X} @karinajonina {GH} @kjonina {MN} @kjonina<br>
  Data: {tt_source}
  "
)

tt_title_text    <- str_glue("Worldwide Bureaucracy Indicators")

```

# Load the weekly Data

```{r Load}

tt <- tt_load("2024-04-30")

```


# Readme

```{r Readme, eval = interactive()}

tt

```


# Glimpse Data

```{r Glimpse}

tt %>% 
  map(glimpse)

```

# Wrangle

```{r Wrangle}
wwbi_data <- tt$wwbi_data
wwbi_series <- tt$wwbi_series
wwbi_country <- tt$wwbi_country

```
# Cleaning Data

```{r Cleaning Data}

wwbi_data <- tt$wwbi_data
wwbi_series <- tt$wwbi_series
wwbi_country <- tt$wwbi_country


country_name <- wwbi_country %>%
  select(1:3)

# Merging 
df <- merge(wwbi_data, country_name, by = "country_code")
df
```

# Visualize

Using your processed dataset, create your unique visualization.

```{R Setting Saving Options}
camcorder::gg_record(dir = here("outputs"),
  device = "png",
  width = 8, height = 7,
  units = "in", dpi = 320
  )
```
  


```{r}

df %>%
ggplot(aes(x = table_name, y = value)) +
  geom_line(linewidth=1.25) +
  

  labs(title = tt_title_text,
       # subtitle = tt_subtitle_text,
       caption = tt_caption,
       colour = "",
       x = "Countries",
       y = "Cumulative Count") + 
 theme( 
   
    plot.background = element_rect(colour=bg_color,fill = bg_color),
    panel.background = element_rect(colour=bg_color,fill = bg_color),
    
    plot.title.position = "plot",
    plot.title = element_textbox_simple(
      halign = 0.5,
      tt_family_2,
      color = txt_color,
      face = "bold",
      size = 100,
      margin = margin(t = 2, r = 0, b = 0, l = 0)
    ),
    
    plot.subtitle = element_textbox_simple(
      halign = 0.5,
      tt_family,
      color = txt_color2,
      #face = "bold",
      size = 80,
      margin = margin(t = 1, r = 0, b = 2, l = 0)
    ),
    
    plot.caption = element_textbox_simple(
      family = tt_family, 
      color = txt_color,
      size = 25,
      lineheight = 0.25,
      margin = margin(t = 1, r = 0, b = 1, l = 2)
    ),
    
    axis.text.x = element_text(size=40,family = tt_family),
    axis.text.y = element_text(size=30,family = tt_family),
    axis.title.x = element_text(size=40,family = tt_family),
    axis.title.y = element_text(size=30,family = tt_family),
    panel.grid.major.y = element_line(colour="black", size=0.1),
    panel.grid.major.x = element_blank(),

    plot.caption.position = "plot",
    legend.position = "none"
    

  )
```


